# Generated by Django 5.2 on 2025-04-26 09:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RoadMap', '0002_major_delete_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('semester', models.CharField(choices=[('1-1', '1st Year, 1st Semester'), ('1-2', '1st Year, 2nd Semester'), ('1-3', '1st Year, 3rd Semester'), ('2-1', '2nd Year, 1st Semester'), ('2-2', '2nd Year, 2nd Semester'), ('2-3', '2nd Year, 3rd Semester'), ('3-1', '3rd Year, 1st Semester'), ('3-2', '3rd Year, 2nd Semester'), ('3-3', '3rd Year, 3rd Semester')], max_length=10)),
                ('major', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='RoadMap.major')),
            ],
        ),
    ]
