# Generated by Django 5.2 on 2025-05-02 14:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RoadMap', '0003_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='major',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roadmap_courses', to='RoadMap.major'),
        ),
        migrations.CreateModel(
            name='Map',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weeks', models.JSONField(default=dict)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roadmap_maps', to='RoadMap.course')),
                ('major', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roadmap_maps', to='RoadMap.major')),
            ],
        ),
    ]
